name: Running Bash Script inside Docker Container
on: [workflow_dispatch]
jobs:
  run_bash_in_docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: run bash script inside docker container
        uses: docker://node:20.3-alpine3.17
        with:
          entrypoint: ./script.sh
          args: "some string"

        