name: Cache Update Workflow
on: [workflow_dispatch]
jobs:
  cache_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Update cache
      
        id: id_cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{runner.os}}-npm-package-${{hashFiles('package-lock.json')}}
          restore-keys: ${{runner.os}}-npm-package-
      - name: Display cache status
        run: |
          echo "cache status: ${{toJson(steps)}}"
      - name: Install dependencies
        run: |
          npm install
      - name: Use axios to make API callss
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            const response = await axios('https://icanhazdadjoke.com/', {
            headers: { 'Accept': 'text/plain' }
            });
            console.log(response.data);