name: Checkout Repository
on: [push]
jobs:
    checkout_repository:
      runs-on: ubuntu-latest
      steps:
        - name: display working directory
          run: pwd
        - name: diplay list of files
          run : ls -a
        - name: display git hub actor
          run: echo $git-hub_actor
        - name: github token
          run: echo ${{ secrets.TOKEN}}
        - name: checkout code
          run: |
            git init
            git remote add origin https://git-hub_actor:${{secrets.TOKEN}}/@github.com/$GITHUB_REPOSITORY.git
            git fetch origin
            git checkout main

        - name: display list of files after checkout
          run: ls -a
        