name: Checkout Actions test
on: [push]
jobs:
  Checkout_Action_job:
    runs-on: ubuntu-latest
    steps:
      - name: Display Current working directorys
        run: pwd
      - name: List files before Checkout
        run: ls -a
      - name: Checkout Actions Repository
        uses: actions/checkout@v3
      - name: List files after Checkout
        run: ls -a

  Display_list_of_files:
    runs-on: ubuntu-latest
    steps:
      - name : List files in the Repository
        run: ls -a