name: Concurrency Test 1
run-name: Concurrency 1
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: environment
concurrency: 
  group: concurrency 1
  cancel-in-progress: true
jobs:
  concurrency-test-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Display github action name
        run : echo "the action is  ${{inputs.environment}}"
      - name: wait for 30 second
        run: sleep 30