name: Concurrency Test 2
run-name: ${{github.workflow}}-Concurrency 2
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: environment
concurrency:
  group: ${{github.workflow}}-concurrency1-${{github.ref}}
  cancel-in-progress: true
jobs:
  concurrency-test-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Display github action name
        run: echo "the action is ${{inputs.environment}}"
      - name: wait for 30 second
        run: sleep 30
