name: Cron Schedule
on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  cron-schedule-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo the cron schedule is triggered
        run: echo "cron schedule is triggered"