name: Expression Context Workflow
on: [push, pull_request,workflow_dispatch]
jobs:
  expression-context-job:
    runs-on: ubuntu-latest
    steps:
      - name: Below are expresion on objects 
        id: expression-step
        run: |
            echo ${{ 4 }}
            echo ${{ 4 < 5 }}
            echo ${{ null }}
            echo ${{ true }}
            echo ${{ true && false }}
            echo ${{ true || (true && false) }}
      - name: github context
        id: github-context
        run: |
            echo ${{ '-----------------------------------------github-------------------------------' }}
            echo '${{ toJson(github) }}'
            echo ${{ '-----------------------------------------secrets -------------------------------' }}
            echo "${{ toJson(secrets) }}"
            echo ${{ '-----------------------------------------steps-------------------------------' }}
            echo "${{toJson(steps)}}"
            echo ${{ '-----------------------------------------runner--------------------------------'}}
            echo "${{toJson(runner)}}"

