name: Fail Fast Matrix
on: [push]
permissions:
  contents: read
jobs:
  failfast-matrix-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        majversion: [1, 2, 3]
        include:
          - majversion: 4
            tag-name: true
    steps:
      - name: displaying version of node
        run: echo '${{toJson(matrix)}}'


