name: GitHub Action Target Branch
on:
  push:
    paths:
      - '.github/workflows/github_action_target_branch.yaml'
jobs:
  github-action-target-branch-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display Target Branch Namessss
        run: |
          echo "The target branch for this action is $GITHUB_REF"
      - name: Display Commit SHA
        run: |
          echo "The commit SHA for this action is $GITHUB_SHA"