name: GitHub Event Workflow
on: [push]
jobs:
    github-event-job:
      runs-on: ubuntu-latest
      steps:
        - name: Display Github event parameters
          run: |
            echo "Event Name: ${{ github.event_name }}"
            echo "Event Path: ${{ github.event_path }}"
            echo "Event Ref: ${{ github.event.ref }}"
            echo "Repository: ${{ github.repository }}"
            echo "Actor: ${{ github.actor }}"
            echo "Workflow: ${{ github.workflow }}"
            echo "Job: ${{ github.job }}"
            echo "Run ID: ${{ github.run_id }}"
            echo "Run Number: ${{ github.run_number }}"
            echo "Action: ${{ github.action }}"
            echo "Sender: ${{ github.event.sender.login }}"
        - name: Display github sha and ref
          run: |
            echo "Github sha is $GITHUB_SHA"
            echo "Github ref is $GITHUB_REF"