name: If Event
on: [push, pull_request, issues, workflow_dispatch]
jobs:
  if-event-job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: expresssions test
        run: |
            echo ${{ 'when push is called' }}
            echo ${{ 2 > 1 }}
            echo '${{ toJson(github)}}'
  if-issue-event-job:
    if: ${{ contains('push', github.event_name) }}
    runs-on: ubuntu-latest
    steps:
       - name: expressions push event contains
         run: |
            echo ${{ 'when push is called in issue event using contains' }}
            echo ${{ 3 > 1 }}
            
            
  if-push-issue-together-job:
    if: ${{ contains(fromJson('["push","issues"]'), github.event_name) }}
    runs-on: ubuntu-latest
    steps:
      - name: expressions push and issue event contains
        run: |
            echo ${{ 'when push or issue is called in push and issue event using contains' }}
            echo ${{ 5 > 1 }}
            echo '${{ toJson(github)}}'
      - name: Display bug event name from issue
        if: contains(github.event.issue.labels.*.name, 'bug')
        run: |
            echo ${{ join(github.event.issue.labels.*.name,',') }}