name: matrix workflow
on: [push]
permissions:
  contents: read
jobs:
  matrix-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        majversion: [1, 2, 3]
        minversion: [14, 16, 18]
        includes:
          - majversion: 4
            test-name: true
          
      #max-parallel:  2
    continue-on-error: true
        
    steps:
      - name: displaying version of node
        run: echo " displaying version of node"
    
      - name: Display Matrix Values
        run: |
          echo "Node.js major version: ${{ matrix.majversion }}"
          echo "Node.js version: ${{ matrix.minversion }}"