name: matrix workflow
on: [push]
permissions:
  contents: read
jobs:
  matrix-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        major-version: [1, 2, 3]
        minor-version: [14, 16, 18]
        includes:
          - major-version: 1
            test-name: true
          - experimental: true
      #max-parallel:  2
    continue-on-error: true
        
    steps:
      - name: displaying version of node
        run: echo " displaying version of node"
    
      - name: Display Matrix Values
        run: |
          echo "Node.js major version: ${{ matrix.major-version }}"
          echo "Node.js version: ${{ matrix.minor-version }}"