name: matrix workflow
on: [push]
permissions:
  contents: read
jobs:
  matrix-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        major-version: [1, 2, 3]
        minor-version: [14, 16, 18]
        includes:
          - major-version: 1
            test-name: 'temp'
          - major-version: 100
            minor-version: 200
            test-name: 'temp2'
      #max-parallel:  2
    continue-on-error: true
        
    steps:
      - name: displaying version of node
        run: echo " displaying version of node"
      - name: if minor version is 14
        if: success() && matrix.minor-version == 14
        run: |
            echo "sleeping for 70 seconds for minor version 14"
            echo '${{ toJson(matrix) }}'
    
      - name: Display Matrix Values
        run: |
          echo "Node.js major version: ${{ matrix.major-version }}"
          echo "Node.js version: ${{ matrix.minor-version }}"