name: Nested workflow yaml
on:
  workflow_dispatch:
    inputs:
      name:
        description: name of person
        type: string

jobs:
  nested_workflow_calling:
    uses: ./.github/workflows/workflow_output.yaml
    with:
      name: ${{inputs.name}}
      secrets: inherit
  display_job:
    runs-on: ubuantu_latest
    needs: nested_workflow_calling
    steps:
      - name: display 
        run: |
            echo '${{toJson(jobs)}}'
            echo  "displaying steps ${{toJson(steps)}}"

    
