name: Private Actions Greetings Workflow
on: [push]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: list files
        run: |
            pwd
            ls -la .github/actions/greet
            ls -la ./
            ls -la ../

      - name: Greet using private action
        id: greet
        uses: ./.github/actions/greet
        with:
          name: Shankar
      - name: show greeting date
        run: echo "'${{fromJson(steps.greet.outputs.date)}}'"

      - name: display environment variable set by action
        run: echo "${env.Hello-Time}