name: Private Actions Docker
on: [ push ]
jobs:
  privaita_acrions_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: calling private action
        id: docker_hello_world_action
        uses: ./.github/actions/docker_hello_world
        with:
          greet_hello: "shankar"
      - name: Get output
        run: |
          echo "Greeting made on : ${{toJson(steps)}}"
      - name: show log on docker
        run: |
            echo " greeting made on ${{env.HELLO_TIME}}"
            echo "greeting made on $Hello_time"
