name: Private Actions Greetings Workflow
on: [push]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: list files
        run: |
            pwd

      - name: Greet using private action
        id: greet
        uses: ./github/actions/greet
        with:
          who-to-greet: Shankar
      - name: show greeting date
        run: echo '${{toJson(steps)}}'

      - name: display environment variable set by action
        run: echo "${env.HELLO-TIME}"