name: Workflow Event
on: 
  workflow_run:
    workflows: [GitHub Action Target Branch]
    types: [completed,failed]
jobs:
  workflow_event_job:
    runs-on: ubuntu-latest
    steps:
      - name: display running after pull target action
        run: |
          echo "running after the pull target action"
      - name: displaying current branch reference and commit code...
        run: |
          echo "current refrence is $GITHUB_REF"
          echo "current sha is $GITHUB_SHA"
