name: workflow_event_test3
on:
  workflow_run:
    workflows: ["Workflow Event"]
    types: [completed]
jobs:
    workflow_event_test3_job:
      runs-on: ubuntu-latest
      steps:
        - name: display running after workflow event action
          run: |
            echo "running after the workflow event action"
        - name: displaying current branch reference and commit code...
          run: |
            echo "current refrence is $GITHUB_REF"
            echo "current sha is $GITHUB_SHA"
