name: workflow_dispatch
on:
  workflow_dispatch:
    inputs:
      string_input:
        description: 'A string input'
        required: true
        default: 'default value'
        type: string

      boolean_input:
        description: 'A boolean input'
        required: true
        default: False
        type: boolean

      optional_input:
        description: 'An optional input'
        required: true
        default: 'option3'
        type: choice
        options:
          - option1
          - option2
          - option3

jobs:
    handle_inputs:
      runs-on: ubuntu-latest
      steps:
        - name: display string input
          run: echo "displaying string ${{ inputs.string_input }}"
        - name: display boolean input
          run: echo ${{ inputs.boolean_input }}
        - name: display optional input
          run: echo ${{ inputs.optional_input }}
        - name: display github branch ref
          run: echo $GITHUB_REF
        