name: Joke Composite Action Workflow
on: [push]
jobs:
  joke_composite_action_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  
      - name: Call Joke Composite Action
        id: joke_composite_action
        uses: ./.github/actions/joke_composite
        with:
          funny_joke: "true"
          upload_joke: "false"
      - name: Get output
        run: | 
          echo "joke told : ${{steps.joke_composite_action.outputs.joke_output}}"
          echo "full step details : ${{toJson(steps)}}"