name: Workflow Commands Example
on: [push]


jobs:
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps:
            - name: testing workflow commands
              run: echo "Hello, Workflow Commands!"
            - name: setting error code
              run: echo "::error::this is a simulated error message"
            